repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
    exclude: '.*\.tla'
  - id: check-added-large-files
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

- repo: local
  hooks:
  - id: remove-pluscal-translation
    name: Remove Generated PlusCal Translation
    entry: ./scripts/pre-commit-hooks/remove_pluscal_translation.sh
    language: script
    files: \.tla$
